steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/scholarstream-i4i/scholarstream-frontend'
      - '-f'
      - 'Dockerfile.frontend'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://scholarstream-backend-1086434452502.us-central1.run.app'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyDaR2t8zhg9c7GiB35ad11wwrYjLOePseE'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=scholarstream-i4i.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=scholarstream-i4i'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=scholarstream-i4i.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=1086434452502'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:1086434452502:web:18f8e8068b2006b1278137'
      - '.'
images:
  - 'gcr.io/scholarstream-i4i/scholarstream-frontend'
